### ISSUE TITLE
docker安装完20210628版本后，点击公共模板出现问题

### ISSUE THREAD

**Issue by happyfengle** [qd-today/qd#105]
![360截图-976614531](https://user-images.githubusercontent.com/34908598/129003917-8987b1ee-dabd-48bb-a5e7-a94dd4e11953.jpg)
按照已CLOSE的一个ISSUES“20210628版本的签到框架打开公共模板需要六七分钟，并且无法显示出模板”，在OPENWRT中操作后，仍然无法解决。如果是防火墙问题，应该如何解决？而且点击公共模板，页面立刻显示图片所示。错误代码如下：
Traceback (most recent call last):
  File "/usr/src/app/web/handlers/subscribe.py", line 41, in get
    res = requests.get(hfile_link, verify=False)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/qiandao-today/templates@master/tpls_history.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9abcf96d50>: Failed to establish a new connection: [Errno -3] Try again',))
这里的Errno -3 不知道代表什么错误？

**Comment by asdaragon** [comment]
#22
coolsnowwolf/lede#1760
@Lee917 参考这个设置一下docker网络，或者使用host模式运行
