### ISSUE TITLE
签到一直提示database or disk is full

### ISSUE THREAD

**Issue by googooog** [qd-today/qd#106]
[E 210816 10:25:04 gen:833] Multiple exceptions in yield list
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 828, in callback
        result_list.append(f.result())
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "/usr/src/app/worker.py", line 250, in do
        self.db.tasklog.add(task['id'], success=False, msg=unicode(e))
      File "/usr/src/app/db/tasklog.py", line 38, in add
        return self._insert(**insert)
      File "/usr/src/app/db/basedb.py", line 102, in _insert
        dbcur = self._execute(sql_query, values.values())
      File "/usr/src/app/db/basedb.py", line 40, in _execute
        dbcur.execute(sql_query, values)
    OperationalError: database or disk is full

是什么原因啊

**Comment by asdaragon** [comment]
@googooog 磁盘空间满了或者没有写入权限

**Comment by googooog** [comment]
> @googooog 磁盘空间满了或者没有写入权限

我查看了磁盘空间还剩余很多，昨天还可以正常签到，今天就提示这个了

**Comment by asdaragon** [comment]
@googooog  df -h 截图看看

**Comment by googooog** [comment]
![image](https://user-images.githubusercontent.com/26278416/129507700-3a8bb8ac-7fef-4990-abae-e202db0b6ed4.png)

**Comment by googooog** [comment]
> @googooog df -h 截图看看

我用的是N1，已经截图了，感谢大佬帮忙。我刚才删除重新安装docker，还是一样的提示。

**Comment by googooog** [comment]
确实是空间满了，清除了logs已经可以用了。
谢谢
