### ISSUE TITLE
更新最新版本后含中文域名的模板出现599错误

### ISSUE THREAD

**Issue by Ovler-Young** [qd-today/qd#112]
同机开了不同docker迁移更新，其中一个含中文域名模板在旧版本（20210628）中正常，在目前最新版本（20210807）中出现599错误
![image](https://user-images.githubusercontent.com/44089074/131315868-c0813484-8962-442b-be8d-1709363b340d.png)

有关 docker-compose logs 如下：
>  [E 210830 16:41:37 web:1789] Uncaught exception POST /har/test (*)
     HTTPServerRequest(protocol='https', host='*', method='POST', uri='/har/test', version='HTTP/1.1', remote_ip='*')
     Traceback (most recent call last):
       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
         result = await result
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
         yielded = self.gen.throw(*exc_info)  # type: ignore
       File "/usr/src/app/web/handlers/har.py", line 73, in post
         ret = yield self.fetcher.fetch(data)
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
         value = future.result()
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
         yielded = self.gen.throw(*exc_info)  # type: ignore
       File "/usr/src/app/libs/fetcher.py", line 403, in fetch
         raise e
       File "/usr/src/app/libs/fetcher.py", line 400, in fetch
         response = yield self.client.fetch(req)
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
         value = future.result()
     tornado.curl_httpclient.CurlError: HTTP 599: Failed sending HTTP request
 [E 210830 16:41:37 web:1789] Uncaught exception POST /har/test (13.94.30.83)
     HTTPServerRequest(protocol='https', host='*', method='POST', uri='/har/test', version='HTTP/1.1', remote_ip=‘*')
     Traceback (most recent call last):
       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
         result = await result
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
         yielded = self.gen.throw(*exc_info)  # type: ignore
       File "/usr/src/app/web/handlers/har.py", line 73, in post
         ret = yield self.fetcher.fetch(data)
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
         value = future.result()
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
         yielded = self.gen.throw(*exc_info)  # type: ignore
       File "/usr/src/app/libs/fetcher.py", line 403, in fetch
         raise e
       File "/usr/src/app/libs/fetcher.py", line 400, in fetch
         response = yield self.client.fetch(req)
       File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
         value = future.result()
     tornado.curl_httpclient.CurlError: HTTP 599: Failed sending HTTP request
 [E 210830 16:41:37 web:2239] 500 POST /har/test (*) 329.75ms

之后经测试，http下的中文域名能正常访问，https下的中文域名均无法正常访问，http与https下的非中文域名均无问题。

**Comment by a76yyyy** [comment]
能提供一个相关的中文域名或者测试har么？

**Comment by a76yyyy** [comment]
经过复现，发现是pycurl模组问题，尝试卸载pycurl可解决该问题
1.进入docker shell
`docker exec -it qiandao /bin/bash`
2.执行卸载pycurl命令
`pip uninstall -y pycurl`

**Comment by Ovler-Young** [comment]
> 经过复现，发现是 pycurl 模组问题，尝试卸载 pycurl 可解决该问题
> 1. 进入 docker shell
> `docker exec -it qiandao /bin/bash`
> 2. 执行卸载 pycurl 命令
> `pip uninstall -y pycurl`

问题部分解决。
当中文域名请求头中没有以 : 开头的请求时问题已解决
当中文域名请求头中存在以 : 开头的请求时，在编辑签到-测试处500，在运行时仍599错误
当非中文域名请求头中存在以 : 开头的请求时无问题

**Comment by Ovler-Young** [comment]
[测试.zip](https://github.com/AragonSnow/qiandao/files/7082275/default.zip)
内含测试用har

**Comment by a76yyyy** [comment]
根据测试har，卸载pycurl后一切正常，请检查容器中是否还有pycurl模组，如果没有的话，请提供一下docker日志和主机环境信息

**Comment by Ovler-Young** [comment]
> 根据测试 har，卸载 pycurl 后一切正常，请检查容器中是否还有 pycurl 模组，如果没有的话，请提供一下 docker 日志和主机环境信息

重启后正常
