### ISSUE TITLE
[Bug] 添加 AES_KEY 和 COOKIE_SECRET 变量后登录失败

### ISSUE THREAD

**Issue by sunjx97** [qd-today/qd#209]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20211228

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

求教 AES_KEY 和 COOKIE_SECRET 应该怎样设置，我设置后登录会失败，显示 500: Internal Server Error。删除两变量后则能正常进入qiandao。

### Describe the Bug

设置变量 AES_KEY 和 COOKIE_SECRET 后登录会失败，显示 500: Internal Server Error。

### QianDao log

```shell
[E 220119 21:13:21 web:1789] Uncaught exception POST /login (10.10.201.9)
    HTTPServerRequest(protocol='http', host='10.10.25.8', method='POST', uri='/login', version='HTTP/1.1', remote_ip='10.10.201.9')
    Traceback (most recent call last):
      File "/usr/src/app/db/user.py", line 135, in decrypt
        old = tmp = crypto.aes_decrypt(data, userkey)
      File "/usr/src/app/libs/mcrypto.py", line 50, in aes_decrypt
        aes = AES.new(key, AES.MODE_CBC, iv)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 232, in new
        return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
        return modes[mode](factory, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
        cipher_state = factory._create_base_cipher(kwargs)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 92, in _create_base_cipher
        if len(key) not in key_size:
    TypeError: object of type 'int' has no len()
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/src/app/web/handlers/login.py", line 52, in post
        if self.db.user.challenge(email, password):
      File "/usr/src/app/db/user.py", line 80, in challenge
        password_hash = self.decrypt(user['id'], user['password'])
      File "/usr/src/app/db/user.py", line 144, in decrypt
        raise self.UserDBException('decrypt error')
    db.user.UserDB.UserDBException: decrypt error
[E 220119 21:13:21 web:1789] Uncaught exception POST /login (10.10.201.9)
    HTTPServerRequest(protocol='http', host='10.10.25.8', method='POST', uri='/login', version='HTTP/1.1', remote_ip='10.10.201.9')
    Traceback (most recent call last):
      File "/usr/src/app/db/user.py", line 135, in decrypt
        old = tmp = crypto.aes_decrypt(data, userkey)
      File "/usr/src/app/libs/mcrypto.py", line 50, in aes_decrypt
        aes = AES.new(key, AES.MODE_CBC, iv)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 232, in new
        return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
        return modes[mode](factory, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
        cipher_state = factory._create_base_cipher(kwargs)
      File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/AES.py", line 92, in _create_base_cipher
        if len(key) not in key_size:
    TypeError: object of type 'int' has no len()
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/src/app/web/handlers/login.py", line 52, in post
        if self.db.user.challenge(email, password):
      File "/usr/src/app/db/user.py", line 80, in challenge
        password_hash = self.decrypt(user['id'], user['password'])
      File "/usr/src/app/db/user.py", line 144, in decrypt
        raise self.UserDBException('decrypt error')
    db.user.UserDB.UserDBException: decrypt error
```

### Expected behavior

可以正常登录

**Comment by a76yyyy** [comment]
两个变量需要在容器全新安装时才能修改

**Comment by sunjx97** [comment]
意思是创建时连挂载的目录也要是全新吗，我是在容器新创建时启用的这两个变量，但是挂载了旧容器的目录（包含数据库那些，不为空）

**Comment by a76yyyy** [comment]
> 意思是创建时连挂载的目录也要是全新吗，我是在容器新创建时启用的这两个变量，但是挂载了旧容器的目录（包含数据库那些，不为空）

数据库中存储的就是这些key加密后的数据

**Comment by a76yyyy** [comment]
后续有时间尝试加个修改的逻辑吧

**Comment by sunjx97** [comment]
> > 意思是创建时连挂载的目录也要是全新吗，我是在容器新创建时启用的这两个变量，但是挂载了旧容器的目录（包含数据库那些，不为空）
> 
> 数据库中存储的就是这些key加密后的数据

了解了👌
