### ISSUE TITLE
提示500: Internal Server Error

### ISSUE THREAD

**Issue by dan3577** [qd-today/qd#235]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20210628

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 32位

### To Reproduce

点我的签到旁的+号，提示如下：
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>

### Describe the Bug

上传HAR提示500: Internal Server Error错误

### QianDao config

```shell
docker pull asdaragon/qiandao
docker run -d --name qiandao -p 9527:80 asdaragon/qiandao
```

### QianDao log

```shell
[E 220320 10:41:28 web:1591] Uncaught exception GET /task/new (192.168.2.205)
    HTTPServerRequest(protocol='http', host='192.168.2.109:9527', method='GET', uri='/task/new', version='HTTP/1.1', remote_ip='192.168.2.205', headers={'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.2.109:9527', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.2.109:9527/my/', 'Cookie': '_xsrf=2|aa5bd8bc|c6846875d92f5c408e6f40f8852d1a94|1647743625; user="2|1:0|10:1647743641|4:user|96:hcQEcm9sZaVhZG1pbsQOZW1haWxfdmVyaWZpZWQAxAhuaWNrbmFtZcDEAmlkAcQFZW1haWywODYxMDEwMDM2QHFxLmNvbQ==|22b706b2de84d2dfecbea6cfbc3e491197667ae341fcbb213930626d6fd08880"'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/src/app/web/handlers/task.py", line 39, in get
        tplid = int(tplid)
    TypeError: int() argument must be a string or a number, not 'NoneType'
[E 220320 10:41:28 web:1591] Uncaught exception GET /task/new (192.168.2.205)
    HTTPServerRequest(protocol='http', host='192.168.2.109:9527', method='GET', uri='/task/new', version='HTTP/1.1', remote_ip='192.168.2.205', headers={'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.2.109:9527', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.2.109:9527/my/', 'Cookie': '_xsrf=2|aa5bd8bc|c6846875d92f5c408e6f40f8852d1a94|1647743625; user="2|1:0|10:1647743641|4:user|96:hcQEcm9sZaVhZG1pbsQOZW1haWxfdmVyaWZpZWQAxAhuaWNrbmFtZcDEAmlkAcQFZW1haWywODYxMDEwMDM2QHFxLmNvbQ==|22b706b2de84d2dfecbea6cfbc3e491197667ae341fcbb213930626d6fd08880"'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/src/app/web/handlers/task.py", line 39, in get
        tplid = int(tplid)
    TypeError: int() argument must be a string or a number, not 'NoneType'
[E 220320 10:41:28 web:2064] 500 GET /task/new (192.168.2.205) 8.50ms
[E 220320 10:41:28 web:2064] 500 GET /task/new (192.168.2.205) 8.50ms
```

### Expected behavior

解决500: Internal Server Error错误

### Screenshots

![image](https://user-images.githubusercontent.com/52194615/159145931-e4623b4e-b2ef-49d2-b95c-ea7b739ab7b6.png)

**Comment by acooler15** [comment]
没有添加签到模板吧？

**Comment by dan3577** [comment]
第一次使用，，不知道怎么添加，正在找教程

**Comment by acooler15** [comment]
docker镜像仓库地址已更换为[https://hub.docker.com/r/a76yyyy/qiandao](https://hub.docker.com/r/a76yyyy/qiandao)

**Comment by acooler15** [comment]
具体信息看 [本项目的README](https://github.com/qiandao-today/qiandao/blob/master/README.md)

**Comment by dan3577** [comment]
好的谢谢

**Comment by a76yyyy** [comment]
更换docker并添加模板后还有问题么？如果没有问题的话请手动关闭issue
