### ISSUE TITLE
[Bug] 更新最新版以后，docker无法启动了，报错。

### ISSUE THREAD

**Issue by iamjimmycheng** [qd-today/qd#245]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220410

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

重建一个新的docker容器，问题依旧。

### Describe the Bug

docker无法启动，且无法获取ip地址。

### QianDao log

```shell
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 51, in <module>
    http_server = HTTPServer(Application(), xheaders=True)
  File "/usr/src/app/web/app.py", line 34, in __init__
    self.jinja_env = jinja2.Environment(
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 51, in <module>
    http_server = HTTPServer(Application(), xheaders=True)
  File "/usr/src/app/web/app.py", line 34, in __init__
    self.jinja_env = jinja2.Environment(
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 51, in <module>
    http_server = HTTPServer(Application(), xheaders=True)
  File "/usr/src/app/web/app.py", line 34, in __init__
    self.jinja_env = jinja2.Environment(
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 51, in <module>
    http_server = HTTPServer(Application(), xheaders=True)
  File "/usr/src/app/web/app.py", line 34, in __init__
    self.jinja_env = jinja2.Environment(
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 51, in <module>
    http_server = HTTPServer(Application(), xheaders=True)
  File "/usr/src/app/web/app.py", line 34, in __init__
    self.jinja_env = jinja2.Environment(
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 51, in <module>
    http_server = HTTPServer(Application(), xheaders=True)
  File "/usr/src/app/web/app.py", line 34, in __init__
    self.jinja_env = jinja2.Environment(
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'autoescape'
```

### Expected behavior

希望可以修复。

**Comment by a76yyyy** [comment]
我看一下你的容器配置,记得去除隐私信息

新版本里源码已经去掉这个extension了,你看看是不是你把源码目录映射了出来,导致源码还是旧版本的源码

**Comment by jxyjest** [comment]
同样的问题，
/data 和/usr/src/app 现在是不是可以删除了，只留下/usr/src/app/config

**Comment by jxyjest** [comment]
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ONNXRUNTIME_TAG=v1.11.0
DDDDOCR_VERSION=master
PYCURL_SSL_LIBRARY=openssl
CURL_VERSION=7.82.0
PORT=80
TZ=CST-8

**Comment by a76yyyy** [comment]
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ONNXRUNTIME_TAG=v1.11.0 DDDDOCR_VERSION=master PYCURL_SSL_LIBRARY=openssl CURL_VERSION=7.82.0 PORT=80 TZ=CST-8

需要看的是你配置容器的目录映射配置

**Comment by jxyjest** [comment]
> > PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ONNXRUNTIME_TAG=v1.11.0 DDDDOCR_VERSION=master PYCURL_SSL_LIBRARY=openssl CURL_VERSION=7.82.0 PORT=80 TZ=CST-8
> 
> 需要看的是你配置容器的目录映射配置

/usr/src/app/config------/root/qiandao/config
/usr/src/app------poratainer的一个文件
/data------poratainer的一个文件

**Comment by a76yyyy** [comment]
> > > PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ONNXRUNTIME_TAG=v1.11.0 DDDDOCR_VERSION=master PYCURL_SSL_LIBRARY=openssl CURL_VERSION=7.82.0 PORT=80 TZ=CST-8
> > 
> > 
> > 需要看的是你配置容器的目录映射配置
> 
> /usr/src/app/config------/root/qiandao/config /usr/src/app------poratainer的一个文件 /data------poratainer的一个文件

/usr/src/app/config------/root/qiandao/config

仅保留这个

**Comment by a76yyyy** [comment]
@iamjimmycheng @jxyjest

请问问题是否解决？

**Comment by jxyjest** [comment]
赞美
