### ISSUE TITLE
[Bug] 分组名称以数字开头会导致账号登录显示500错误

### ISSUE THREAD

**Issue by crossgg** [qd-today/qd#261]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220410

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

分组名称：如果是数字开头，会导致账号登录不了 显示：500: Internal Server Error。

### Describe the Bug

分组名称：如果是数字开头，会导致账号登录不了 显示：500: Internal Server Error。

### QianDao log

```shell
[I 220513 20:23:29 run:95] Http Server started on 0.0.0.0:80


[W 220513 20:23:40 redisdb:27] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.


开启det后自动关闭ocr


[I 220513 20:23:43 run:95] Http Server started on 0.0.0.0:80


[I 220513 20:24:43 web:2239] 304 GET /login (172.17.0.1) 269.05ms


[I 220513 20:24:51 web:2239] 302 POST /login (172.17.0.1) 523.42ms


[E 220513 20:24:51 web:1789] Uncaught exception GET /my/ (172.17.0.1)


    HTTPServerRequest(protocol='http', host='10.0.0.10:8923', method='GET', uri='/my/', version='HTTP/1.1', remote_ip='172.17.0.1')


    Traceback (most recent call last):


      File "/usr/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute


        result = await result


      File "/usr/src/app/web/handlers/my.py", line 75, in get


        await self.render('my.html', tpls=tpls, tasks=tasks, my_status=my_status, userid=user['id'], taskgroups=_groups,  tplgroups=tplgroups, adminflg=adminflg)


      File "/usr/lib/python3.10/site-packages/tornado/web.py", line 863, in render


        html = self.render_string(template_name, **kwargs)


      File "/usr/src/app/web/handlers/base.py", line 47, in render_string


        return template.render(namespace)


      File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render


        self.environment.handle_exception()


      File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 926, in handle_exception


        raise rewrite_traceback_stack(source=source)


      File "/usr/src/app/web/tpl/my.html", line 1, in top-level template code


        {% extends "base.html" %}


      File "/usr/src/app/web/tpl/base.html", line 93, in top-level template code


        {% block body %}{% endblock %}


      File "/usr/src/app/web/tpl/my.html", line 64, in block 'body'


        {% for group in taskgroups | sort(reverse=True) %}


      File "/usr/lib/python3.10/site-packages/jinja2/filters.py", line 409, in do_sort


        return sorted(value, key=key_func, reverse=reverse)


    TypeError: '<' not supported between instances of 'str' and 'int'


[E 220513 20:24:51 web:2239] 500 GET /my/ (172.17.0.1) 281.90ms
```

**Comment by acooler15** [comment]
@a76yyyy 旧数据库的task表的“_groups"字段为VARBINARY(128)，应该是这个问题导致的。
sqlite3旧数据库的转储SQL：
```
CREATE TABLE "task" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tplid" INT UNSIGNED NOT NULL,
  "userid" INT UNSIGNED NOT NULL,
  "disabled" TINYINT(1) NOT NULL DEFAULT 0,
  "init_env" BLOB,
  "env" BLOB,
  "session" BLOB,
  "last_success" INT UNSIGNED,
  "last_failed" INT UNSIGNED,
  "success_count" INT UNSIGNED NOT NULL DEFAULT 0,
  "failed_count" INT UNSIGNED NOT NULL DEFAULT 0,
  "last_failed_count" INT UNSIGNED NOT NULL DEFAULT 0,
  "next" INT UNSIGNED DEFAULT NULL,
  "note" VARCHAR(256),
  "ctime" INT UNSIGNED NOT NULL,
  "mtime" INT UNSIGNED NOT NULL,
  "ontimeflg" INT UNSIGNED NOT NULL DEFAULT 0,
  "ontime" VARCHAR(256) NOT NULL DEFAULT '00:10:00',
  "groups" VARCHAR(256) NOT NULL DEFAULT 'None',
  "pushsw" VARBINARY(128) NOT NULL DEFAULT '{"logen":false,"pushen":true}',
  "newontime" VARBINARY(256) NOT NULL DEFAULT '{"sw":false,"time":"00:10:10","randsw":false,"tz1":0,"tz2":0}',
  "_groups" VARBINARY(128) NOT NULL DEFAULT 'None',
  "retry_count" INT NOT NULL DEFAULT 8,
  "retry_interval" INT UNSIGNED
);
```
新建sqlite3数据库的转储SQL：
```
CREATE TABLE "task" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tplid" INT UNSIGNED NOT NULL,
  "userid" INT UNSIGNED NOT NULL,
  "disabled" TINYINT(1) NOT NULL DEFAULT 0,
  "init_env" BLOB,
  "env" BLOB,
  "session" BLOB,
  "retry_count" INT NOT NULL DEFAULT 8,
  "retry_interval" INT UNSIGNED,
  "last_success" INT UNSIGNED,
  "last_failed" INT UNSIGNED,
  "success_count" INT UNSIGNED NOT NULL DEFAULT 0,
  "failed_count" INT UNSIGNED NOT NULL DEFAULT 0,
  "last_failed_count" INT UNSIGNED NOT NULL DEFAULT 0,
  "next" INT UNSIGNED DEFAULT NULL,
  "note" VARCHAR(256),
  "ctime" INT UNSIGNED NOT NULL,
  "mtime" INT UNSIGNED NOT NULL,
  "ontimeflg" INT UNSIGNED NOT NULL DEFAULT 0,
  "ontime" VARCHAR(256) NOT NULL DEFAULT '00:10:00',
  "_groups" VARCHAR(256) NOT NULL DEFAULT 'None',
  "pushsw" VARBINARY(128) NOT NULL DEFAULT '{"logen":false,"pushen":true}',
  "newontime" VARBINARY(256) NOT NULL DEFAULT '{"sw":false,"time":"00:10:10","randsw":false,"tz1":0,"tz2":0}'
);
```
