### ISSUE TITLE
这个是啥问题呢？

### ISSUE THREAD

**Issue by zxjack** [qd-today/qd#3]
昨天docker部署了，今天进行签到测试，报错了，查看log如下，请指教。
Traceback (most recent call last):

      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute

        result = yield result

      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run

        value = future.result()

      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result

        raise_exc_info(self._exc_info)

      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper

        yielded = next(result)

      File "/usr/src/app/web/handlers/task.py", line 137, in post

        taskpushsw = json.loads(task['pushsw'])

      File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads

        return _default_decoder.decode(s)

      File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode

        obj, end = self.raw_decode(s, idx=_w(s, 0).end())

      File "/usr/local/lib/python2.7/json/decoder.py", line 380, in raw_decode

        obj, end = self.scan_once(s, idx)

    ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by asdaragon** [comment]
网站返回的值里面有" 但是没有使用转义\"，导致解析成json失败。
是只有一个网站这样还是所有的？

**Comment by zxjack** [comment]
我是测试了smzdm的模块，目前就测试了这一个

**Comment by asdaragon** [comment]
@zxjack 
sorry,没注意看。是读取数据库的值 task['pushsw']  这个值时出错，跟网站没什么关系。你是什么情况下点了测试报错的？

**Comment by zxjack** [comment]
我用docker部署成功了之后，在网页上提交了模块，然后第二天运行就报错了，重启了docker之后依然是报错的。

![qiandao](https://user-images.githubusercontent.com/9455090/83826697-20829c00-a70f-11ea-8f07-ce5d565a7f5d.png)
![qiandao01](https://user-images.githubusercontent.com/9455090/83826731-32fcd580-a70f-11ea-804f-d78a086296ee.png)
![qiandao02](https://user-images.githubusercontent.com/9455090/83826738-36905c80-a70f-11ea-9d10-0c47ce2429e1.png)

**Comment by zxjack** [comment]
我docker运行的命令是：
docker run -d --name qiandao -p 12345:80 -v $(pwd)/qiandao/config:/usr/src/app/config -v /etc/localtime:/etc/localtime --restart always asdaragon/qiandao

**Comment by asdaragon** [comment]
@zxjack 我试了一下，是我写入得初始值有问题，一两天内修复，我会通知你的

**Comment by zxjack** [comment]
thx

**Comment by AragonSnow** [comment]
@zxjack 
已经修复，需要重新部署一下。

**Comment by asdaragon** [comment]
@zxjack 
已经修复，重新部署一下。
```
docker stop qiandao
docker rm qiandao
rm -rf qiandao/config
docker run -d --name qiandao -p 12345:80 -v $(pwd)/qiandao:/usr/src/app -v  --restart always asdaragon/qiandao
cd qiandao
git clone https://github.com/AragonSnow/qiandao.git .
docker restart qiandao
```

**Comment by zxjack** [comment]
我刚刚重新部署了，测试了之后发现还有些问题呢。今天我已经签到了，明天上午我再试试看。log如下：（cookie部分我删除了）
   HTTPServerRequest(protocol='http', host='192.168.0.20:12345', method='POST', uri='/task/1/run', version='HTTP/1.1', remote_ip='192.168.0.183', headers={'Origin': 'http://192.168.0.20:12345', 'Content-Length': '0', 'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.0.20:12345', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.0.20:12345/my/', 'Cookie': '
    Traceback (most recent call last):


      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute


        result = yield result


      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run


        value = future.result()


      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result


        raise_exc_info(self._exc_info)


      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper


        yielded = next(result)


      File "/usr/src/app/web/handlers/task.py", line 137, in post


        taskpushsw = json.loads(task['pushsw'])


      File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads


        return _default_decoder.decode(s)


      File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode


        obj, end = self.raw_decode(s, idx=_w(s, 0).end())


      File "/usr/local/lib/python2.7/json/decoder.py", line 380, in raw_decode


        obj, end = self.scan_once(s, idx)


    ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)


[E 200605 16:28:50 web:1591] Uncaught exception POST /task/1/run (192.168.0.183)


    HTTPServerRequest(protocol='http', host='192.168.0.20:12345', method='POST', uri='/task/1/run', version='HTTP/1.1', remote_ip='192.168.0.183', headers={'Origin': 'http://192.168.0.20:12345', 'Content-Length': '0', 'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.0.20:12345', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.0.20:12345/my/', 'Cookie': '_

    Traceback (most recent call last):


      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute


        result = yield result


      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run


        value = future.result()


      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result


        raise_exc_info(self._exc_info)


      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper


        yielded = next(result)


      File "/usr/src/app/web/handlers/task.py", line 137, in post


        taskpushsw = json.loads(task['pushsw'])


      File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads


        return _default_decoder.decode(s)


      File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode


        obj, end = self.raw_decode(s, idx=_w(s, 0).end())


      File "/usr/local/lib/python2.7/json/decoder.py", line 380, in raw_decode


        obj, end = self.scan_once(s, idx)


    ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)


[E 200605 16:28:50 web:2064] 500 POST /task/1/run (192.168.0.183) 10.08ms


[E 200605 16:28:50 web:2064] 500 POST /task/1/run (192.168.0.183) 10.08ms

**Comment by zxjack** [comment]
奇怪我再提交脚本那边进行测试是可以测试成功的。

**Comment by asdaragon** [comment]
从错误上看还是之前的错误，应该是你重启缓存没更新。

**Comment by zxjack** [comment]
怎么更新缓存？你说的是浏览器的缓存吗？
