### ISSUE TITLE
[Bug] 最新版20220828容器启动失败

### ISSUE THREAD

**Issue by 907739769** [qd-today/qd#311]
### Verify steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220828

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

启动失败
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)

### Describe the Bug

启动失败
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)

### QianDao config

```shell
version: "3"

services:
  qiandao:
    image: a76yyyy/qiandao:latest
    # image: a76yyyy/qiandao:lite-latest
    container_name: qiandao
    depends_on:
      - redis
    ports:
      - "1223:80"
    volumes:
      - /volume1/docker/qiandao/config:/usr/src/app/config"
    environment:
      # - QIANDAO_DEBUG=False
      # - MULTI_PROCESS=False
      # - AUTO_RELOAD=False
      # - GZIP=True
      - BIND=0.0.0.0
      - PORT=80
      - ENABLE_HTTPS=True
      # - ACCESS_LOG=True
      - DOMAIN=xxxx
      # - USE_PYCURL=True
      # - ALLOW_RETRY=True
      # - DNS_SERVER=
      # - CURL_ENCODING=True
      # - CURL_CONTENT_LENGTH=True
      # - NOT_RETRY_CODE=301|302|303|304|305|307|400|401|403|404|405|407|408|409|410|412|415|413|414|500|501|502|503|504|599
      # - EMPTY_RETRY=True
      # - COOKIE_DAY=5
      # - JAWSDB_MARIA_URL=mysql://user:pass@localhost:3306/dbname?auth_plugin=
      - REDISCLOUD_URL=redis://redis:6379
      # - TRACEBACK_PRINT=False
      # - PUSH_PIC_URL=https://fastly.jsdelivr.net/gh/a76yyyy/qiandao@master/web/static/img/push_pic.png
      # - PUSH_BATCH_SW=True
      # - DB_TYPE=sqlite3
      # - REDIS_DB_INDEX=1
      # - QIANDAO_EVIL=1000
      - PBKDF2_ITERATIONS=400
      - AES_KEY=asdasdx2sad
      - COOKIE_SECRET=dasdasd
      # - CHECK_TASK_LOOP=500
      # - DOWNLOAD_SIZE_LIMIT=5242880
      # - REQUEST_TIMEOUT=30.0
      # - CONNECT_TIMEOUT=30.0
      # - DELAY_MAX_TIMEOUT=29.9
      # - PROXIES=
      # - PROXY_DIRECT_MODE=regexp
      # - PROXY_DIRECT=(?xi)\A([a-z][a-z0-9+\-.]*://)?(0(.0){3}|127(.0){2}.1|localhost|\[::([\d]+)?\])(:[0-9]+)?
      # - EXTRA_ONNX_NAME=
      # - EXTRA_CHARSETS_NAME=
      # - NEW_TASK_DELAY=1
      - MAIL_SMTP=xxx
      - MAIL_PORT=465
      - MAIL_SSL=True
      - MAIL_USER=xxx
      - MAIL_PASSWORD=xxx
      - MAIL_FROM=xxx
      # - MAIL_DOMAIN=
      # - MAILGUN_KEY=
      # - USER0ISADMIN=True

  redis:
    image: redis:alpine
    container_name: redis
    command: ["--loglevel warning"]
    # command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - /volume1/docker/qiandao/redis/data:/data:rw
```

### QianDao log

```shell
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
```

### Expected behavior

启动成功

### Screenshots

启动失败
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)
TypeError: AlchemyMixin._insert() got an unexpected keyword argument 'regEn'
Traceback (most recent call last):
  File "/usr/src/app/db/db_converter.py", line 253, in ConvertNewType
    raise Exception("new")
Exception: new
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 256, in ConvertNewType
    await self.db.site._insert(**insert)

**Comment by skyshenma** [comment]
最新版的启动失败+1，日志跟楼上大佬一样。

**Comment by a76yyyy** [comment]
@907739769  @skyshenma  bug已定位并修复, 重新拉取一下镜像试试
