### ISSUE TITLE
[Bug] 更新20220828之后无法启动

### ISSUE THREAD

**Issue by gitiray** [qd-today/qd#313]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20220828 lite

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

watchtower 自动更新并重建容器后，网站掉线

### Describe the Bug

自动更新所以 Docker 配置不变，Qiandao 配置最近也没改过

已经看过 https://github.com/qiandao-today/qiandao/issues/311 由于我是早上更新的，这个时候已经是最新镜像了

没有启用 redis 所以 `Connect Redis falied` 应该是预期行为，可以忽略
针对 `duplicate column name: password_md5` 检查过配置，是只有一列字段的

### QianDao log

```shell
[W 220829 12:09:25 qiandao.RedisDB redisdb:27] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
[W 220829 12:09:25 qiandao.RedisDB redisdb:27] Connect Redis falied: Error 99 connecting to localhost:6379. Address not available.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
    raise error
  File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: duplicate column name: password_md5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/run.py", line 57, in <module>
    loop.run_until_complete(run)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/src/app/db/db_converter.py", line 411, in ConvertNewType
    await exec_shell("ALTER TABLE `user` ADD  `password_md5` VARBINARY(128) NOT NULL DEFAULT '' ")
  File "/usr/src/app/db/basedb.py", line 87, in _execute
    result = await sql_session.execute(text)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 215, in execute
    result = await greenlet_spawn(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
    raise error
  File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: password_md5
[SQL: ALTER TABLE `user` ADD  `password_md5` VARBINARY(128) NOT NULL DEFAULT '' ]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Expected behavior

正常启动

**Comment by mathlife** [comment]
我也是类似问题，相对好一点的事网站还在线，就是不少任务签到是500错误，退回20220728版本后全部正常

**Comment by gitiray** [comment]
> 我也是类似问题，相对好一点的事网站还在线，就是不少任务签到是500错误，退回20220728版本后全部正常

我也先回退0728了，一切正常，先保证签到任务不耽误，等大佬看看怎么处理

**Comment by a76yyyy** [comment]
```
  File "/usr/src/app/db/db_converter.py", line 411, in ConvertNewType
    await exec_shell("ALTER TABLE `user` ADD  `password_md5` VARBINARY(128) NOT NULL DEFAULT '' ")
```
这里显示 411行

最新推送的版本里对应行代码是第398行

可能是本地docker镜像未重新拉取或者镜像源未及时更新, 重新拉取镜像或者拉取指定版本试试

```
docker pull a76yyyy/qiandao:lite-20220828
```

**Comment by a76yyyy** [comment]
备份数据库后通过源码方式更新到最新版源码后尝试

```
# 先进入容器后台, 执行命令后重启容器 
wget https://gitee.com/a76yyyy/qiandao/raw/master/update.sh -O /usr/src/app/update.sh && \
sh /usr/src/app/update.sh -f
```

还不行的话在环境变量里设置 `QIANDAO_DEBUG=True` 开启调试模式后重启容器抓取相关日志

**Comment by mathlife** [comment]
进容器内更新后暂时没出问题，过0点我再试试

**Comment by saint886** [comment]
我的问题是旧的模板签到，但是在签到模板编辑页面Cookie选项的勾没有了，测试也没有cookie

**Comment by a76yyyy** [comment]
> 我的问题是旧的模板签到，但是在签到模板编辑页面Cookie选项的勾没有了，测试也没有cookie

fix by https://github.com/qiandao-today/qiandao/commit/8acc5939d8ee931a12eada9a9201037658ddf048

尝试更新源码至最新

**Comment by loveqianool** [comment]
最新的容器，一部分任务出现五百，部分又正常。
```
[34m[D 220901 01:50:13 asyncio selector_events:54](B[m Using selector: EpollSelector
开启det后自动关闭ocr
[32m[I 220901 01:50:13 qiandao.Run run:75](B[m Http Server started on 0.0.0.0:80
[32m[I 220901 01:50:13 qiandao.Worker worker:37](B[m Schedule Worker start...
[34m[D 220901 01:50:13 qiandao.Worker worker:127](B[m Schedule Producer started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 0 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 1 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 2 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 3 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 4 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 5 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 6 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 7 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 8 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 9 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 10 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 11 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 12 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 13 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 14 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 15 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 16 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 17 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 18 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 19 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 20 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 21 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 22 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 23 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 24 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 25 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 26 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 27 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 28 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 29 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 30 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 31 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 32 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 33 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 34 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 35 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 36 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 37 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 38 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 39 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 40 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 41 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 42 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 43 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 44 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 45 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 46 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 47 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 48 started
[34m[D 220901 01:50:13 qiandao.Worker worker:112](B[m Runner 49 started
[32m[I 220901 01:50:15 tornado.access web:2271](B[m 304 GET /my/ (172.26.0.1) 251.36ms
[31m[E 220901 01:50:17 tornado.application web:1798](B[m Uncaught exception GET /task/44/edit (172.26.0.1)
    HTTPServerRequest(protocol='https', host='qiandao.sss.com', method='GET', uri='/task/44/edit', version='HTTP/1.0', remote_ip='172.26.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
        self.dialect.do_execute(
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
        cursor.execute(statement, parameters)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
        self._adapt_connection._handle_exception(error)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
        raise error
      File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
        self.await_(_cursor.execute(operation, parameters))
      File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
        return current.driver.switch(awaitable)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
        value = await result
      File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
        await self._execute(self._cursor.execute, sql, parameters)
      File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
        return await self._conn._execute(fn, *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
        return await future
      File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
        result = function()
    sqlite3.OperationalError: Could not decode to UTF-8 column 'init_env' with text '��`�<��s@��>��I��M�aW��B�5[����K\5_xkT��e10�V����0��OX��-[�f*��Ro*�.Z&1A��J��@�
.�Z-m.dc����@��;t�3J�'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/usr/src/app/web/handlers/task.py", line 134, in get
        task['init_env'] = (await self.db.user.decrypt(user['id'], (await self.db.task.get(taskid, ('init_env',)))['init_env']))
      File "/usr/src/app/db/task.py", line 85, in get
        result = await self._get(smtm, one_or_none=one_or_none, first=first, sql_session=sql_session)
      File "/usr/src/app/db/basedb.py", line 92, in _get
        result: Result = await sql_session.execute(stmt)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 215, in execute
        result = await greenlet_spawn(
      File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
        result = context.throw(*sys.exc_info())
      File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
        result = conn._execute_20(statement, params or {}, execution_options)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
        return meth(self, args_10style, kwargs_10style, execution_options)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
        return connection._execute_clauseelement(
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
        ret = self._execute_context(
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
        self._handle_dbapi_exception(
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
        util.raise_(
      File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
        raise exception
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
        self.dialect.do_execute(
      File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
        cursor.execute(statement, parameters)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
        self._adapt_connection._handle_exception(error)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
        raise error
      File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
        self.await_(_cursor.execute(operation, parameters))
      File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
        return current.driver.switch(awaitable)
      File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
        value = await result
      File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
        await self._execute(self._cursor.execute, sql, parameters)
      File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
        return await self._conn._execute(fn, *args, **kwargs)
      File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
        return await future
      File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
        result = function()
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Could not decode to UTF-8 column 'init_env' with text '��`�<��s@��>��I��M�aW��B�5[����K\5_xkT��e10�V����0��OX��-[�f*��Ro*�.Z&1A��J��@�
.�Z-m.dc����@��;t�3J�'
    [SQL: SELECT task.init_env 
    FROM task 
    WHERE task.id = ?]
    [parameters: ('44',)]
    (Background on this error at: https://sqlalche.me/e/14/e3q8)
[31m[E 220901 01:50:17 tornado.access web:2271](B[m 500 GET /task/44/edit (172.26.0.1) 18.94ms
```
```
Traceback (most recent call last): File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context self.dialect.do_execute( File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute cursor.execute(statement, parameters) File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute self._adapt_connection._handle_exception(error) File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception raise error File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute self.await_(_cursor.execute(operation, parameters)) File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only return current.driver.switch(awaitable) File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn value = await result File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute await self._execute(self._cursor.execute, sql, parameters) File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute return await self._conn._execute(fn, *args, **kwargs) File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute return await future File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run result = function() sqlite3.OperationalError: Could not decode to UTF-8 column 'init_env' with text '��`�<��s@��>��I��M�aW��B�5[����K\5_xkT��e10�V����0��OX��-[�f*��Ro*�.Z&1A��J��@� .�Z-m.dc����@��;t�3J�' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute result = await result File "/usr/src/app/web/handlers/task.py", line 134, in get task['init_env'] = (await self.db.user.decrypt(user['id'], (await self.db.task.get(taskid, ('init_env',)))['init_env'])) File "/usr/src/app/db/task.py", line 85, in get result = await self._get(smtm, one_or_none=one_or_none, first=first, sql_session=sql_session) File "/usr/src/app/db/basedb.py", line 92, in _get result: Result = await sql_session.execute(stmt) File "/usr/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 215, in execute result = await greenlet_spawn( File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn result = context.throw(*sys.exc_info()) File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute result = conn._execute_20(statement, params or {}, execution_options) File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20 return meth(self, args_10style, kwargs_10style, execution_options) File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection return connection._execute_clauseelement( File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement ret = self._execute_context( File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context self._handle_dbapi_exception( File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception util.raise_( File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_ raise exception File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context self.dialect.do_execute( File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute cursor.execute(statement, parameters) File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute self._adapt_connection._handle_exception(error) File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception raise error File "/usr/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute self.await_(_cursor.execute(operation, parameters)) File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only return current.driver.switch(awaitable) File "/usr/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn value = await result File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute await self._execute(self._cursor.execute, sql, parameters) File "/usr/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute return await self._conn._execute(fn, *args, **kwargs) File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute return await future File "/usr/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run result = function() sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Could not decode to UTF-8 column 'init_env' with text '��`�<��s@��>��I��M�aW��B�5[����K\5_xkT��e10�V����0��OX��-[�f*��Ro*�.Z&1A��J��@� .�Z-m.dc����@��;t�3J�' [SQL: SELECT task.init_env FROM task WHERE task.id = ?] [parameters: ('44',)] (Background on this error at: https://sqlalche.me/e/14/e3q8)

```

**Comment by a76yyyy** [comment]
> 最新的容器，一部分任务出现五百，部分又正常。

docker最新版本已推送, 请更新后看还有没有问题

**Comment by loveqianool** [comment]
> 

更新到九月一号，之前五百的正常了，暂时未发现问题。
