### ISSUE TITLE
群晖docker 除了挂载/usr/src/app/config 之外，挂载其他目录均异常停止

### ISSUE THREAD

**Issue by zhengfan2014** [qd-today/qd#33]
个人想修改代码默认的boostrap主题，但是无论是挂载/usr/src/app/或者/usr/src/app/web 均会容器异常停止
日志如下
```
07:00:02     Traceback (most recent call last):
07:00:02     File "/usr/src/app/run.py", line 14, in <module>
07:00:02     from web.app import Application
07:00:02     File "/usr/src/app/web.py", line 15, in <module>
07:00:02     from web.app import Application
07:00:02     ImportError: No module named app
```
挂载的文件夹均给了everyone全部权限，并给予了容器最高权限，但是还是报错

**Comment by asdaragon** [comment]
。。。
docker 挂载时是本地目录覆盖容器内的，你直接覆盖文件夹是直接清空文件夹。正确方法如下：
```
docker run -d --name qiandao -p 12345:80 -v $(pwd)/qiandao:/usr/src/app asdaragon/qiandao
cd  $(pwd)/qiandao
git clone https://github.com/AragonSnow/qiandao.git .
docker restart qiandao
```
