### ISSUE TITLE
[Bug] (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by Aiome** [qd-today/qd#363]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230111

### Bug on OS

Windows

### Bug on Platform

Code Build/Windows x64

### To Reproduce

 python ./run.py

### Describe the Bug

启动报错，sqlite问题

### QianDao log

```shell
[W 230129 19:14:03 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 10061 connecting to localhost:6379. 由于目标计算机积极拒绝，无法连接。.
[W 230129 19:14:07 qiandao.RedisDB redisdb:28] Connect Redis falied: Error 10061 connecting to localhost:6379. 由于目标计算机积极拒绝，无法连接。.
[D 230129 19:14:07 asyncio proactor_events:623] Using proactor: IocpProactor
Traceback (most recent call last):
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 493, in checkout
    rec = pool._do_get()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 388, in __init__
    self.__connect()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 299, in connect
    await_only(connection),
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 145, in _connect
    self._connection = await future
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 405, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Code\qiandao-20230111\run.py", line 54, in <module>
    loop.run_until_complete(run)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Code\qiandao-20230111\db\db_converter.py", line 36, in ConvertNewType
    await exec_shell('''CREATE TABLE IF NOT EXISTS `user` (
  File "D:\Code\qiandao-20230111\db\basedb.py", line 90, in _execute
    result = await sql_session.execute(text)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 214, in execute
    result = await greenlet_spawn(
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\future\engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 493, in checkout
    rec = pool._do_get()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\impl.py", line 256, in _do_get
    return self._create_connection()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 388, in __init__
    self.__connect()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\pool\base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 299, in connect
    await_only(connection),
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 145, in _connect
    self._connection = await future
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
  File "C:\Users\mahongyan18\AppData\Local\Programs\Python\Python39\lib\site-packages\aiosqlite\core.py", line 405, in connector
    return sqlite3.connect(loc, **kwargs)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Expected behavior

无

**Comment by a76yyyy** [comment]
待修复
临时解决方案: 在qiandao源码目录下建一个config空文件夹
