### ISSUE TITLE
安装完毕后 上传 保存 500

### ISSUE THREAD

**Issue by BlueSkyClouds** [qd-today/qd#4]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2898, in wrapper
     return method(self, *args, **kwargs)
File "/usr/src/app/web/handlers/har.py", line 108, in post
har = self.db.user.encrypt(userid, data['har'])
File "/usr/src/app/db/user.py", line 102, in encrypt
raise self.UserDBException('encrypt error')
UserDBException: encrypt error

**Comment by asdaragon** [comment]
@BlueskyClouds 
因为没有注册账号，需要登出-注册账号-登出-登陆
