### ISSUE TITLE
[Bug] 无法连接外置数据库

### ISSUE THREAD

**Issue by saltzmanchan** [qd-today/qd#404]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QianDao Version

20230228

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

按文档及源码配置docker环境变量 mysql及redis

![image](https://user-images.githubusercontent.com/47584257/230863532-c7e9a21e-0f71-4c78-afa3-15dc15e1b0b6.png)

```
mysql://qiandao:'dCK#KqR9^2'@192.168.17.17:3306/qiandao
redis://rediscloud:'I!L7xcE#3fMh1'@192.168.17.17:6379
```

启动项目

![image](https://user-images.githubusercontent.com/47584257/230862676-7c41a913-f1f1-468c-9a06-6d86da9e13a8.png)

![image](https://user-images.githubusercontent.com/47584257/230862819-fea80354-f2d5-493d-87bb-9c281500c1b7.png)

### Describe the Bug

配置mysql和redis后无法正确解析链接地址

### QianDao log

```shell
2023-04-10 07:30:05	stdout	  File "/usr/src/app/config.py", line 49, in mysql
2023-04-10 07:30:05	stdout	    class mysql(object):
2023-04-10 07:30:05	stdout	  File "/usr/src/app/config.py", line 47, in <module>
2023-04-10 07:30:05	stdout	    import config
2023-04-10 07:30:05	stdout	  File "/usr/src/app/run.py", line 11, in <module>
2023-04-10 07:30:05	stdout	Traceback (most recent call last):
2023-04-10 07:30:00	stdout	ValueError: Port could not be cast to integer value as "'dCK"
2023-04-10 07:30:00	stdout	    raise ValueError(f"Port could not be cast to integer value as {port!r}")
2023-04-10 07:30:00	stdout	  File "/usr/lib/python3.11/urllib/parse.py", line 173, in port
2023-04-10 07:30:00	stdout	           ^^^^^^^^^^^^^^
2023-04-10 07:30:00	stdout	    port = mysql_url.port or '3306'                                         # MySQL的端口Port
2023-04-10 07:30:00	stdout	  File "/usr/src/app/config.py", line 49, in mysql
2023-04-10 07:30:00	stdout	    class mysql(object):




File "/usr/src/app/config.py", line 77, in redis
2023-04-10 07:21:19	stdout	    class redis(object):
2023-04-10 07:21:19	stdout	  File "/usr/src/app/config.py", line 75, in <module>
2023-04-10 07:21:19	stdout	    import config
2023-04-10 07:21:19	stdout	  File "/usr/src/app/run.py", line 11, in <module>
2023-04-10 07:21:19	stdout	Traceback (most recent call last):
2023-04-10 07:21:15	stdout	ValueError: Port could not be cast to integer value as 'I!L78ppxcE'
2023-04-10 07:21:15	stdout	    raise ValueError(f"Port could not be cast to integer value as {port!r}")
2023-04-10 07:21:15	stdout	  File "/usr/lib/python3.11/urllib/parse.py", line 173, in port
2023-04-10 07:21:15	stdout	           ^^^^^^^^^^^^^^
2023-04-10 07:21:15	stdout	    port = redis_url.port or 6379                                           # Redis的端口Port
```

### Expected behavior

希望能提供合适的链接格式以连接外置数据库

**Comment by a76yyyy** [comment]
1. 密码无需引号包裹
2. 请不要使用 `#` 这类url特殊符号作为用户名密码
