### ISSUE TITLE
[Bug] 不稳定问题之一，出现599，PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by aogg** [qd-today/qd#460]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20230718

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

签到https://console.openfrp.net/web/frp/api/userSign

### Describe the Bug

```
[W 230815 10:42:40 QD.Http.Fetcher fetcher:489] POST https://console.openfrp.net/web/frp/api/userSign [Warning] HTTP 599: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1) -> Try to retry!
[E 230815 10:42:40 QD.Http.Fetcher fetcher:493] HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Traceback (most recent call last):
  File "/usr/src/app/libs/fetcher.py", line 470, in build_response
    response =  await self.client.fetch(req)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.curl_httpclient.CurlError: HTTP 599: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
[D 230815 10:42:40 QD.Http.CookieJar cookiejar:1682] extract_cookies: 
[D 230815 10:42:40 charset_normalizer api:439] Encoding detection: ascii is most likely the one.
[E 230815 10:42:40 QD.Web.Handler task:201] taskid:7 tplid:1 failed! 1.4351s 
    Failed at 2/2 request, 
    Fail assert: {"re": "200", "from": "status"} from success_asserts, 
    Response Error : HTTP 599: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1), 
    Request URL: https://console.openfrp.net/web/frp/api/userSign

```

### QD log

```shell
[W 230815 10:42:40 QD.Http.Fetcher fetcher:489] POST https://console.openfrp.net/web/frp/api/userSign [Warning] HTTP 599: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1) -> Try to retry!
[E 230815 10:42:40 QD.Http.Fetcher fetcher:493] HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Traceback (most recent call last):
  File "/usr/src/app/libs/fetcher.py", line 470, in build_response
    response =  await self.client.fetch(req)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.curl_httpclient.CurlError: HTTP 599: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
[D 230815 10:42:40 QD.Http.CookieJar cookiejar:1682] extract_cookies: 
[D 230815 10:42:40 charset_normalizer api:439] Encoding detection: ascii is most likely the one.
[E 230815 10:42:40 QD.Web.Handler task:201] taskid:7 tplid:1 failed! 1.4351s 
    Failed at 2/2 request, 
    Fail assert: {"re": "200", "from": "status"} from success_asserts, 
    Response Error : HTTP 599: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1), 
    Request URL: https://console.openfrp.net/web/frp/api/userSign

```
```


### Expected behavior

之前网站挂了，现在网站好了，结果签到就坏了

### Screenshots

_No response_

**Comment by a76yyyy** [comment]
599一般是网络和网站服务器问题
抽时间我测试一下

**Comment by aogg** [comment]
我已经换个开源项目了，这个项目是我用过的bug问题最多的项目

**Comment by a76yyyy** [comment]
> 我已经换个开源项目了，这个项目是我用过的bug问题最多的项目

很抱歉这个项目让你不满意，祝您继续愉快使用其他开源项目

**Comment by Goldenbeef** [comment]
openfrp这个跟框架没关系，是网站套cf了

**Comment by a76yyyy** [comment]
已测试, 对端 OpenFrp 问题, 非框架问题.

如有疑问请 reopen 这个 issue.

> PS: 框架开发者非独立开发者, 不以 QD-Today 组织内项目及代码进行盈利、商业和接受捐赠服务等活动, 因此项目维护开发精力实在有限, 如果因此导致您使用框架过程中产生不愉快的体验, 请您见谅.
>
> 对于您在使用中有任何问题, 非常感谢您能够尽可能提交完善的 Issue 信息反馈.
>
> 同时也欢迎您提交 PR, 来为开源世界注入新的活力.

**Comment by duchenpaul** [comment]
遇到一样的错, 使用proxy扶墙解决
