### ISSUE TITLE
[Bug] python3.9貌似不兼容了

### ISSUE THREAD

**Issue by Doublefire-Chen** [qd-today/qd#508]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20240210

### Bug on OS

Linux

### Bug on Platform

Code Build/Linux 64位

### To Reproduce

环境：Ubuntu22.04, Python 3.9.5
使用源码安装，python run.py

### Describe the Bug

报错：
```
Traceback (most recent call last):
  File "/var/www/sign/run.py", line 18, in <module>
    from db import DB, db_converter
  File "/var/www/sign/db/__init__.py", line 13, in <module>
    from db.redisdb import RedisDB
  File "/var/www/sign/db/redisdb.py", line 14, in <module>
    from libs.utils import is_lan
  File "/var/www/sign/libs/utils.py", line 84, in <module>
    def varbinary2ip(addr: bytes | int | str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

### QD log

```shell
Traceback (most recent call last):
  File "/var/www/sign/run.py", line 18, in <module>
    from db import DB, db_converter
  File "/var/www/sign/db/__init__.py", line 13, in <module>
    from db.redisdb import RedisDB
  File "/var/www/sign/db/redisdb.py", line 14, in <module>
    from libs.utils import is_lan
  File "/var/www/sign/libs/utils.py", line 84, in <module>
    def varbinary2ip(addr: bytes | int | str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
```


### Expected behavior

也许要更新一下wiki了，我后来使用python3.11可以跑，3.10没试过，应该也可以。

### Screenshots

_No response_

**Comment by Doublefire-Chen** [comment]
附上wiki地址：https://qd-today.github.io/qd/zh_CN/guide/deployment.html#:~:text=Version%20%3E%3D%20python3.9

**Comment by acooler15** [comment]
3.10是支持的，这个Union新写法是3.10引入的
