### ISSUE TITLE
[Bug] docker 启动时报错 500 Internel Error

### ISSUE THREAD

**Issue by aniude** [qd-today/qd#531]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

最新

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

安装启动时报错

### Describe the Bug

安装启动时报错

### QD log

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/usr/src/app/web/handlers/my.py", line 34, in get
    if (await self.db.user.get(user['id'], fields=('id',))):
                               ~~~~^^^^^^
KeyError: 'id'
```

### Expected behavior

安装启动时报错

**Comment by a76yyyy** [comment]
数据库损坏, 如果有备份数据库请使用备份数据库, 否则请重命名损坏的数据库为 `database.db.bak` 后重启容器以生成全新的数据库

**Comment by hdzj-1981** [comment]
> 数据库损坏，如果有备份数据库请使用备份数据库，否则请重命名损坏的数据库以便`database.db.bak`重启容器以生成全新的数据库

飞牛系统，0.8.19版本， 删除了所有数据库文件，在启动容器，还是报500错误，，黑群晖安装一下就好。不知道什么问题。

**Comment by a76yyyy** [comment]
> > 数据库损坏，如果有备份数据库请使用备份数据库，否则请重命名损坏的数据库以便`database.db.bak`重启容器以生成全新的数据库
> 
> 飞牛系统，0.8.19版本， 删除了所有数据库文件，在启动容器，还是报500错误，，黑群晖安装一下就好。不知道什么问题。

没用过这个系统，如果数据库一直错误的话可以尝试切换为MySQL数据库

**Comment by xuanyuanbao** [comment]
同，我是新手，也遇到了这个问题

**Comment by akqzx** [comment]
同，也遇到了这个问题
