### ISSUE TITLE
[Bug] 公共模板更新报错

### ISSUE THREAD

**Issue by magnetpackk** [qd-today/qd#566]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用 最新源码 测试过，问题依旧存在
- [X] Core 这是 QD 框架存在的问题，并非我所使用的 QD 早期版本（如 20210628及之前版号 等）或模板的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### QD Version

20240210

### Bug on OS

Linux

### Bug on Platform

Docker/Linux 64位

### To Reproduce

类似于https://github.com/qd-today/qd/issues/537 中存在的问题，复现步骤一样，按照其中步骤增加加速未能解决

### Describe the Bug

jsdelivr_cdn/jsdelivr_fastly/ghproxy/fastgit等都已经尝试过，未能解决问题
docker终端内直接ping github和https://raw.githubusercontent.com/延迟大约为200ms，连通性没问题

### QD log

```shell
具体日志如下
[E 241226 16:56:30 QD.Web.Handler subscribe:172] UserID: 1 update Subscribe failed! Reason: TimeoutError

    Traceback (most recent call last):

      File "/usr/src/app/web/handlers/subscribe.py", line 108, in update

        async with session.get(hfile_link, verify_ssl=False, timeout=config.request_timeout, proxy=proxy) as res:

      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__

        self._resp = await self._coro

                     ^^^^^^^^^^^^^^^^

      File "/usr/lib/python3.11/site-packages/aiohttp/client.py", line 493, in _request

        with timer:

      File "/usr/lib/python3.11/site-packages/aiohttp/helpers.py", line 725, in __exit__

        raise asyncio.TimeoutError from None

    TimeoutError

[I 241226 16:56:31 tornado.access web:2348] 101 GET /subscribe/1/updating/ (119.237.241.252) 0.84ms

[I 241226 16:56:33 tornado.access web:2348] 200 GET /subscribe/1/ (119.237.241.252) 10.78ms
```

### Expected behavior

可以正常更新

**Comment by a76yyyy** [comment]
github能通的话关闭代理加速试试

**Comment by tufu9441** [comment]
同样的问题，好久没更新过公共模板了，今天点进去想添加个新的签到，发现报错。

**Comment by magnetpackk** [comment]
> github能通的话关闭代理加速试试

都试过了，直连和走镜像提示是一样的。
没有用代理，是改了hosts

**Comment by a76yyyy** [comment]
最新版更新了加速地址，可以试试

**Comment by crossgg** [comment]
https://github.com/qd-today/qd/issues/581#issuecomment-2661262037
试试这个

**Comment by xiaobei206** [comment]
> github能通的话关闭代理加速试试

怎么关闭代理加速，默认是开启的，然后这些加速网站动不动就倒闭，太烦了，还不如我路由器直接翻了。

**Comment by a76yyyy** [comment]
Close by #607
