### ISSUE TITLE
0122版本无法正常启动了

### ISSUE THREAD

**Issue by q3vJXQtx** [qd-today/qd#59]
更新0122后docker容器无法正常启动了 换回0117后正常启动

**Comment by asdaragon** [comment]
@5sir 重新pull镜像，如果还启动不了 docker logs 容器名 发以下报错信息

**Comment by 5sir** [comment]
emmm 宝塔重新拉取镜像 新建容器后 启动会提示80端口被占用了 我知道是nginx在使用80端口 但是之前我记得没有出现过这个情况

**Comment by q3vJXQtx** [comment]
已解决

**Comment by JunTsao** [comment]
> @5sir 重新pull镜像，如果还启动不了 docker logs 容器名 发以下报错信息

群晖docker，装载了文件夹，从0117升级到0122后，启动失败，升级办法是替换文件夹
附日志供参考，看看能不能帮到您查找问题


```
Traceback (most recent call last):
File "/usr/src/app/run.py", line 14, in <module>
from web.app import Application
File "/usr/src/app/web/app.py", line 16, in <module>
from web.handlers import handlers, ui_modules, ui_methods
File "/usr/src/app/web/handlers/__init__.py", line 22, in <module>    module = __import__('%s.%s' % (__package__, module), fromlist = ["handlers"])
File "/usr/src/app/web/handlers/task.py", line 16, in <module>
from funcs import pusher
File "/usr/src/app/funcs.py", line 8, in <module>
import croniter
ImportError: No module named croniter
```
