### ISSUE TITLE
Docker启动失败，报打不开数据库文件

### ISSUE THREAD

**Issue by liun02163** [qd-today/qd#80]
启动docker失败，于是去掉-d参数，打印日志如下：
[root@centos7]# docker run  --name qiandao -p 12345:80 -v $(pwd)/qiandao/config:/usr/src/app/config asdaragon/qiandao
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 44, in <module>
    converter.ConvertNewType() 
  File "/usr/src/app/sqlite3_db_task_converter.py", line 24, in ConvertNewType
    class DB(object):
  File "/usr/src/app/sqlite3_db_task_converter.py", line 25, in DB
    user = db.UserDB()
  File "/usr/src/app/sqlite3_db/user.py", line 39, in __init__
    )''' % self.__tablename__)
  File "/usr/src/app/db/basedb.py", line 39, in _execute
    dbcur = self.dbcur
  File "/usr/src/app/sqlite3_db/basedb.py", line 45, in dbcur
    self.conn = sqlite3.connect(self.path, isolation_level=None)
sqlite3.OperationalError: unable to open database file

**Comment by asdaragon** [comment]
docker用户没有写入权限？root用户运行试试
