### ISSUE TITLE
启动时报错，请问是什么问题

### ISSUE THREAD

**Issue by langhun** [qd-today/qd#94]
File "/usr/lib/python2.7/site-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python2.7/site-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1101 (42000): BLOB, TEXT, GEOMETRY or JSON column 'repos' can't have a default value

**Comment by asdaragon** [comment]
@langhun 你的Mysql版本是多少，我在我的mysql上测试正常的

**Comment by langhun** [comment]
> @langhun 你的Mysql版本是多少，我在我的mysql上测试正常的

@ @AragonSnow mysql 5.6.50

**Comment by asdaragon** [comment]
@langhun 更新一下试试
```
docker exec -it 容器名 /bin/sh
git config --global credential.helper store
git fetch --all
git reset --hard origin/master
exit
docker restart 容器名
```

**Comment by langhun** [comment]
> @langhun 更新一下试试
> 
> ```
> docker exec -it 容器名 /bin/sh
> git config --global credential.helper store
> git fetch --all
> git reset --hard origin/master
> exit
> docker restart 容器名
> ```

@AragonSnow 
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 44, in 
    converter.ConvertNewType() 
  File "/usr/src/app/sqlite3_db_task_converter.py", line 138, in ConvertNewType
    );''' ) 
  File "/usr/src/app/db/basedb.py", line 40, in _execute
    dbcur.execute(sql_query, values)
  File "/usr/local/lib/python2.7/site-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python2.7/site-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python2.7/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1101 (42000): BLOB/TEXT column 'repos' can't have a default value

还是这样

**Comment by asdaragon** [comment]
@langhun 更新一下镜像

**Comment by langhun** [comment]
> @langhun 更新一下镜像

@AragonSnow 现在可以了，谢谢！
