### ISSUE TITLE
20210628版本的签到框架打开公共模板需要六七分钟，并且无法显示出模板

### ISSUE THREAD

**Issue by Lee917** [qd-today/qd#98]
Traceback (most recent call last):
  File "/usr/src/app/web/handlers/subscribe.py", line 41, in get
    res = requests.get(hfile_link, verify=False)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/qiandao-today/templates@master/tpls_history.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa85327e290>: Failed to establish a new connection: [Errno 110] Operation timed out',))

![屏幕截图 2021-07-02 133430](https://user-images.githubusercontent.com/25250112/124225575-43fa5f00-db3a-11eb-9963-8d9a74393818.png)

您好，我使用的是OpenWrt固件中的Docker-Man，Docker版本是：20.10.7    API版本是：1.41

望回复，谢谢您

**Comment by asdaragon** [comment]
https://github.com/AragonSnow/qiandao/issues/22
https://github.com/coolsnowwolf/lede/issues/1760
@Lee917 参考这个设置一下docker网络，或者使用host模式运行

**Comment by Lee917** [comment]
> #22
> [coolsnowwolf/lede#1760](https://github.com/coolsnowwolf/lede/issues/1760)
> @Lee917 参考这个设置一下docker网络，或者使用host模式运行

嗯，问题解决了，谢谢您
